name: Deploy PDF

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: 
            resume.tex
            resume.cls
      - name: Copy
        run: |
          mkdir output
          cp ./resume.pdf ./output/resume.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: Resume
          path: output/resume.pdf

# name: Build resume LaTex document
# on: [push]
# jobs:
#   build_resume:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up Git repository
#         uses: actions/checkout@v4
#       - name: Compile LaTeX document
#         uses: xu-cheng/latex-action@v3
#         with:
#           root_file: 
#             resume.tex
#             resume.cls
#       - name: Upload PDF file
#         uses: actions/upload-artifact@v4
#         with:
#           name: PDF
#           path: Armando Arevalo Resume.pdf
